<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-07-08 09:01
=======
# Generated by Django 5.0.6 on 2024-07-08 17:09
>>>>>>> 8037ddad579ec674c0d45b197b091f5618bfb524

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to=settings.AUTH_USER_MODEL),
        ),
    ]
