# Generated by Django 5.0.6 on 2024-07-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
