# Generated by Django 5.0.7 on 2024-07-12 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetmodel',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
