FROM node:18.16.0-alpine as build-base

WORKDIR /app
COPY ./forum_frontend /app
RUN npm config delete proxy
RUN npm install && npm run build

FROM nginx:latest

COPY --from=build-base /app/dist /usr/share/nginx/html
COPY ./etc/nginx.conf /etc/nginx/conf.d/default.conf
