version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./forum:/app/forum
    ports:
      - "${WEB_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${FORUM_DB_NAME}
      POSTGRES_USER: ${FORUM_DB_USER}
      POSTGRES_PASSWORD: ${FORUM_DB_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
  
#  celery_worker:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: ["celery", "-A", "forum", "worker", "-l", "INFO"]

volumes:
  postgres_data:
