version: '3.8'

services:
  web:
    build: .
    command: gunicorn forum.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${FORUM_DB_NAME}
      POSTGRES_USER: ${FORUM_DB_USER}
      POSTGRES_PASSWORD: ${FORUM_DB_PASSWORD}
      POSTGRES_HOST: ${FORUM_DB_HOST}
      POSTGRES_PORT: ${FORUM_DB_PORT}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
