kind: ConfigMap
apiVersion: v1
metadata:
  name: forum-configmap
  namespace: default
data:
  forum_db_name: "forum_db"
  forum_db_host: "forum-psql"
  forum_db_port: "5432"

  django_settings_module: "forum.settings"

  forum_email_host: "dummy-smpt-server"
  forum_email_port: "8025"

  forum_redis_host: "forum-redis"
  forum_redis_port: "6379"

  forum_celery_broker_url: "redis://forum-redis:6379/0"

  token_refresh_rate: "1000/hour"

  forum_password_reset_link: "http://link/"

  forum_mongo_host: "forum-mongo"
  forum_mongo_port: "27017"
  forum_mongo_db_name: "forum_db"

  forum_api_host: "forum-internal"
  forum_api_port: "8000"
