apiVersion: v1
kind: Service
metadata:
  name: forum-postgresql
  namespace: default
spec:
  selector:
    app: forum-postgresql
  type: ClusterIP
  ports:
  - name: forum-postgresql
    protocol: TCP
    port: 5432
    targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  forum-postgresql
  namespace: default
  labels:
    app:  forum-postgresql
spec:
  selector:
    matchLabels:
      app: forum-postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app:  forum-postgresql
    spec:
      containers:
      - name:  forum-postgresql
        image:  postgres:13
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: forum-configmap
              key: forum_db_name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: forum-secret
              key: forum_db_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: forum-secret
              key: forum_db_password
        ports:
        - containerPort:  5432
          name:  forum-postgresql
        volumeMounts:
        - name: postgres-volume
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume
          hostPath:
            path: /mnt/volumes/postgresql
      restartPolicy: Always
