apiVersion: v1
kind: Service
metadata:
  name: web-internal
  namespace: default
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: web
          image: nginx # TODO: change image
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: WEB_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: forum-configmap
                  key: web_api_host
            - name: WEB_API_PORT
              valueFrom:
                configMapKeyRef:
                  name: forum-configmap
                  key: web_api_port
      volumes:
        - name: config-volume
          configMap:
            name: forum-configmap
