# Generated by Django 5.0.6 on 2024-07-25 08:41

from django.db import migrations


def fill_startup_size_model(apps, schema_editor):
    StartupSize = apps.get_model("startups", "StartupSize")

    startup_sizes = [
        {"name": "Extra Small", "people_count_min": 1, "people_count_max": 20},
        {"name": "Small", "people_count_min": 21, "people_count_max": 50},
        {"name": "Medium", "people_count_min": 51, "people_count_max": 100},
        {"name": "Large", "people_count_min": 101, "people_count_max": 500},
        {"name": "Extra Large", "people_count_min": 501, "people_count_max": 1000000},
    ]

    for startup_size in startup_sizes:
        StartupSize.objects.create(**startup_size)


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_startup_is_deleted_alter_startup_contacts_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_startup_size_model),
    ]
