# Generated by Django 5.0.6 on 2024-07-05 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_id', models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='NEW', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('business_plan', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration of the project in months', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('startup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startup')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('projects', models.ManyToManyField(related_name='industry', to='projects.project')),
            ],
            options={
                'db_table': 'industry',
            },
        ),
        migrations.CreateModel(
            name='ProjectSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.DecimalField(decimal_places=2, help_text="Investor's share in the project as a percentage", max_digits=5)),
                ('investor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'project_subscription',
            },
        ),
    ]
