# Generated by Django 5.0.7 on 2024-07-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_historicalproject'),
        ('projects', '0002_initial'),
    ]

    operations = [
    ]
