# Generated by Django 5.0.7 on 2024-07-18 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_merge_0002_historicalproject_0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproject',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Project', 'verbose_name_plural': 'historical Projects'},
        ),
        migrations.RenameField(
            model_name='historicalproject',
            old_name='startup_id',
            new_name='startup',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='status_id',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.projectstatus'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the project in months', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
