# Generated by Django 5.0.6 on 2024-07-25 09:24

from django.db import migrations


def fill_project_status_model(apps, schema_editor):
    ProjectStatus = apps.get_model("projects", "ProjectStatus")

    project_statuses = [
        {"title": "NEW", "description": "The project has just been created and has not yet been launched."},
        {"title": "ACTIVE", "description": "The project is now active and is being implemented."},
        {"title": "ON_HOLD", "description": "The project is temporarily stopped or on pause."},
        {"title": "COMPLETED", "description": "The project was successfully completed."},
        {"title": "CANCELLED", "description": "The project has been canceled and will not be continued."},
        {"title": "PENDING", "description": "The project is waiting for confirmation."},
        {"title": "APPROVED", "description": "The project is approved and can be started."},
    ]

    for project_status in project_statuses:
        ProjectStatus.objects.create(**project_status)


def fill_industry_model(apps, schema_editor):
    Industry = apps.get_model("projects", "Industry")

    industries = [
        {"name": "IT", "description": "Information technology and software."},
        {"name": "Fintech", "description": "Financial technologies."},
        {"name": "HealthTech", "description": "Healthcare."},
        {"name": "E-commerce", "description": "Electronic commerce."},
        {"name": "EdTech", "description": "Educational technologies."},
        {"name": "Energy & Environment", "description": "Energy and environment."},
        {"name": "Transport & Logistics", "description": "Transport and logistics."},
        {"name": "PropTech", "description": "Property Technology."},
        {"name": "Media & Entertainment", "description": "Entertainment and media."},
        {"name": "AgTech & FoodTech", "description": "Agricultural technologies and food technologies."},
    ]

    for industry in industries:
        Industry.objects.create(**industry)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_historicalproject_options_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_project_status_model),
        migrations.RunPython(fill_industry_model),
    ]
