name: Run Unit Tests

on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
            cd forum/ 
            python -c "import os; os.environ['DJANGO_SETTINGS_MODULE'] = 'forum.settings'; os.environ['SECRET_KEY'] = '${{ secrets.SECRET_KEY }}'; from django.core.management import execute_from_command_line; execute_from_command_line(['manage.py', 'test'])"