name: Run Unit Tests

on: [push]

jobs:
  test:
    runs-on: windows-latest
    env:
        DJANGO_SETTINGS_MODULE:  ${{ secrets.django_settings_module }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
            cd forum/ 
            poetry run python -c "import os; os.environ['DJANGO_SETTINGS_MODULE'] = 'forum.settings'; import django; django.setup(); import django.test.utils;django.test.utils.get_runner(django.conf.settings)().run_tests([])"