name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pylint-django

      - name: Run pylint
        run: |
          cd forum/
          pylint --load-plugins pylint_django **/*.py 
