name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run pylint
        run: |
          cd forum/
          poetry run pylint --fail-under=3.5 --load-plugins=pylint_django --django-settings-module=forum.settings **/*.py
        continue-on-error: true

      - name: Display pylint output if failed
        if: failure()
        run: cat pylint.logg